### ISSUE TITLE
Need to add a some title/content regarding the CyberSource Payment like other payment methods

### ISSUE THREAD

**Issue by komal-sh-27** [bagisto/bagisto-cybersource-payment#1]
Need to add a some title/content regarding the CyberSource Payment like other payment methods

**How to Reproduce:**

Step 1: Install this module 

Step 2: Click on **Configure -> Payments Methd** in this otpion go to the bottom and here shows **CyberSource Payment** option:

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/9159a005-970d-4078-ba73-10a18d38f348)

**Possible Solution:**

Should be added a  title of cybersource payent method like other payments option

**Comment by gitesh-webkul** [comment]
This issue has been Fixed.

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/121868383/069594df-8c8b-4d19-933c-fe7ca3b5d6fc)

**Comment by komal-sh-27** [comment]
I have checked this issue in **v2.0.0, 2.1.0, 2.1.1** also. In all versions shows a title in payment option:

**V2.0.0:**

![Screenshot from 2024-03-19 19-03-03](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/cc583aec-672b-4656-9a6c-2f1cae26198c)

**V2.1.0, and V2.1.1:**

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/b4b12fe0-2338-4e8c-b2f8-fa15e0625bb3)

![Screenshot from 2024-03-19 19-03-18](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/e550dfa7-bba8-4edb-b846-2482cec2b58d)

So, I am closing this issue.
