### ISSUE TITLE
Here added a translation msg instead of proper msg

### ISSUE THREAD

**Issue by komal-sh-27** [bagisto/bagisto-cybersource-payment#2]
Here added a translation msg instead of proper msg

**How to Reproduce:**

Step 1: Install this module and now click on **Configure -> Payments Methd** in this otpion go to the bottom and here shows **CyberSource Payment** option:

Step 2 Here shows a translation instead of proper msg:

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/25fd7185-1ef4-4d87-a702-869dac1ce9ee)

**`Note: This Translation issue shows in v2.0, but in v2.1.0, 2.1.1 tag not showing like this error`**

**Possible Solution:**

Should be shown a proper msg here like this:

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/14147913-7ffd-44fa-8df2-29596f0184e4)

**Comment by gitesh-webkul** [comment]
This issue has been fixed

**Comment by gitesh-webkul** [comment]
![payment](https://github.com/bagisto/bagisto-cybersource-payment/assets/121868383/a9cfde1b-75d0-4fa6-9bab-a30a8d3a24d5)

**Comment by komal-sh-27** [comment]
I have checked this issue now this issue fixed in v2.0.0.

**Here logo feature is not added in v2.0.0:**

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/2e44ec3d-f450-467b-aca3-051431512f0d)

**But available in v2.1.0 and v2.1.1:**

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/d1085cc8-f449-47d1-895e-6a56ab93fbe5)

So now, I am closing this issue.
