### ISSUE TITLE
When we have enable status is on then shows a warning msg automatically

### ISSUE THREAD

**Issue by komal-sh-27** [bagisto/bagisto-cybersource-payment#3]
When we have enable status is on then shows a warning msg automatically

**How to Reproduce:**

Step 1: Install this module

Step 2: Click on **Configure -> Payments Methd** in this otpion go to the bottom and here shows **CyberSource Payment** option:

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/a00b667c-441d-41c3-beac-3c1d88efc8e9)

**Possible Solution:**

Should be aad a proper msg or not.

**Comment by gitesh-webkul** [comment]
This issue has been Fixed

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/121868383/4e60fdbd-2979-445d-9780-34902439d8ea)

**Comment by komal-sh-27** [comment]
I have checked this issue after new changes, now default warning not showing when we status is enabled or on.

**In V2.0.0:**

![Screenshot from 2024-03-20 10-34-36](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/e114710e-667d-44a4-8e69-9a1a8887e784)

**In V2.1.0:**

![Screenshot from 2024-03-20 10-35-40](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/9f4ff7d6-296d-48e2-8794-592202083059)

**In V2.1.1:**

![Screenshot from 2024-03-20 10-34-46](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/2c4cdcbe-386b-448a-ad51-781203dd7a99)

So I am closing this issue.
