### ISSUE TITLE
 When we doing payment with cybersource payment option then here no need to add a CVN no. while CS payment card

### ISSUE THREAD

**Issue by komal-sh-27** [bagisto/bagisto-cybersource-payment#4]
When we doing payment with cybersource payment option then here no need to add a CVN no. while CS payment card

**How to Reproduce:**

Step 1: Install this module

Step 2: Click on **Configure -> Payments Methd** in this otpion go to the bottom and here shows **CyberSource Payment** option

Step 3: Now add the configurations of this module on cybersource dashboard:

 1. Add below details inside Payment Configuration -> Secure Acceptance Settings -> Edit Profile -> Customer Response -> Transaction Response Page -> Select Hosted By You.  
 
[Ex: http://localhost/bg-cybersource-payment-2.0/public/checkout/cyber-source/response]

2. Add below details inside Payment Configuration -> Secure Acceptance Settings -> Edit Profile -> Customer Response -> Custom Cancel Response Page -> Select Hosted By You.   

[Ex: http://localhost/bg-cybersource-payment-2.0/public/checkout/cyber-source/cancel]

After setting the conf. on cybersource dash. then click  on **profile prompt button** so that **profile activate**, then works fine

Step 4: Now create a product and checkout then here select the cybersoure payment method then redirect on card details page here fill the details but not fill **CVN** no. and after click on **pay button** then payment successfully instead of **CVN no. is required**

**Here select the cybersource payment method:**

![Screenshot from 2024-03-13 13-27-17](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/206159b1-4828-47db-9fac-8e1fcb6dad80)

**Here CVN no. is not filled also click on pay then payment sucessfully created:**

![Screenshot from 2024-03-13 13-27-56](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/fd41ef02-0b76-4e87-b297-75d88eb433c1)

**For more references check the below video:**

https://webkul.chatwhizz.com/share/view-recording/65f13a581dbc90091c40013a

**Possible Solution:**

Should be need to add a CVN while payment page, optherwise shows a warning msg like 'payment is not successfully'

**Comment by gitesh-webkul** [comment]
This is not an issue. Admin need to check CVN option required while setting configurations in the dashboard of cybersource.

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/121868383/e1e83d9c-3c0a-4195-9fce-10e34af28133)


![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/121868383/f71d9493-5939-4258-8cc4-a0e4919f0c4c)

**Comment by komal-sh-27** [comment]
This is not an issue, it is configuration from cybersource panel. We want CVN no is required or not.

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/38cf8403-75f3-48f1-a601-e39cb0e774f8)

So, I am closing this issue.
