### ISSUE TITLE
In v2.1.0, 2.1.1 shows a field error in configuration of cybersource payment method

### ISSUE THREAD

**Issue by komal-sh-27** [bagisto/bagisto-cybersource-payment#5]
In v2.1.0, 2.1.1 shows a field error in configuration of cybersource payment method

**How to Reproduce:**

Step 1: Install this module

Step 2: Click on **Configure -> Payments Methd** in this otpion go to the bottom and here shows **CyberSource Payment option** and shows a option but here in some field not added for add a data for configuration:

**Not showing these fields properly:**

1. Profile Id
2. Access Key
3. Secret Key

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/d0116a08-101b-419f-96de-a203dbccd645)

**`Note: This issue shows on v2.1.0, v2.1.1 release but with v2.0.0 version shows works fine`**

**Possible Solution:**

Should be shows a proper field here so that we can continue this payment after configuration like this, checks in v2.0.0:

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/e7eb4e83-7f21-4b52-b739-bd02aa8b157c)

**Comment by gitesh-webkul** [comment]
This issue has been Fixed.

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/121868383/aed25b5d-966d-44b2-b80f-db95c9999511)

**Comment by komal-sh-27** [comment]
I have checked this issue, now this issue has been resolved with v2.1.0 and also v2.1.1:

**V2.1.0:**

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/8942b74c-d772-4fa0-889a-85ceb9623ce2)

**V2.1.1:**

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/926b8c1e-3151-46b2-9d82-9b87c0b11222)

So, I am closing this issue.
