### ISSUE TITLE
Logo not working shows a default logo instead of uploaded image on front end checkout page

### ISSUE THREAD

**Issue by komal-sh-27** [bagisto/bagisto-cybersource-payment#6]
Logo not working shows a default logo instead of uploaded image on front end checkout page

**How to Reproduce:**

Step 1: Install this module

Step 2: Click on **Configure -> Payments** Methd in this otpion go to the bottom and here shows **CyberSource Payment** option and shows a option but here in some field not added for add a data for configuration. Then here shows a logo option and here select img for logo like this:

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/38c717fd-e43c-4f9b-b24b-39f0a9b15ec4)

Step 3: Now go to the customer panel, and select the cybersource payment method here shows a default img but not showing a correct image which we have choosed on conf. option:

![Screenshot from 2024-03-13 15-01-34](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/dc15eb81-761d-4df2-af73-985848fcab6c)

**Possible Solution:**

Should be shows a selected logo on checkout page on same page not w supporting.\

**Comment by gitesh-webkul** [comment]
This feature is added for bagisto release version after v2.0.0. So kindly, check on that version.

**Comment by komal-sh-27** [comment]
I have checked this issue, now this issue works fine in v2.1.0, and v2.1.1 bagisto.

After added a logo from here then shows in cutsomer panel on checkout page:

![Screenshot from 2024-03-20 11-09-33](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/fb438d60-bcb1-40d5-b401-873c9d32b40e)

So, I am closing this issue.
