### ISSUE TITLE
If we have choose the maximum or above amount from 999$, then shows an error regarding information information is not correct

### ISSUE THREAD

**Issue by komal-sh-27** [bagisto/bagisto-cybersource-payment#7]
If we have choose the maximum or above amount from 999$, then shows an error regarding information information is not correct

**How to Reproduce:**

Step 1: Create a product with 2 amount one is below 999$ and one is above 999$ like 1000$

Step 2: Now checkout these product one by one

Step 3: Here we have check the 1st prod. is successfully ordered with below 999$ or equal price

And next 2nd prod. shows an error regarding amount value error with above 999$ like 1000$ or extra amount

**Error:**

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/63539748/a701d6b5-30a0-436c-ac5a-7e404c7a6101)

**Possible Solution:**

If we have choose any amount then should be ordered successfully.

**Comment by gitesh-webkul** [comment]
This is not an issue. It is the default behaviour of CyberSource Test Environment. Kindly, check below attachment.

![image](https://github.com/bagisto/bagisto-cybersource-payment/assets/121868383/5d97748d-2177-40cd-95f4-5d1e0f8f0f94)

**Comment by komal-sh-27** [comment]
This is not an issue, this is flow of cybersource test in test environment:

https://support.cybersource.com/knowledgebase/knowledgearticle/?code=000002274 

So, I am closing this issue.
